import React, { useState, useEffect, createContext, useContext } from 'react';
import { initializeApp } from 'firebase/app';
import { getAuth, signInAnonymously, signInWithCustomToken, onAuthStateChanged } from 'firebase/auth';
import { getFirestore, collection, addDoc, onSnapshot, deleteDoc, doc, updateDoc, query } from 'firebase/firestore';

// --- Translations Object ---
const translations = {
    en: {
        appName: "Kohinoor Lights",
        home: "Home",
        services: "Services",
        products: "Products",
        book: "Book",
        myBookings: "My Bookings",
        contactNav: "Contact",
        search: "Search...",
        userId: "User ID:",
        loadingApp: "Loading Application...",
        welcomeTitle: "Enhance Your Car's Vision",
        welcomeSubtitle: "One-stop solution for excellent headlights and services.",
        ourServices: "Our Services",
        featuredProducts: "Featured Products",
        view: "View",
        bookAppointment: "Book Appointment",
        contactUs: "Contact Us",
        headlightRestoration: "Headlight Restoration",
        headlightReplacement: "Headlight Replacement",
        fogLightInstallation: "Fog Light Installation",
        mirrorReplacement: "Mirror Replacement",
        newArrivals: "New Arrivals",
        usedParts: "Used Parts",
        specialistBrands: "Specialist Brands",
        headlightRestorationDesc: "Restore dull headlights to their original clarity and brightness.",
        headlightReplacementDesc: "Install new headlights to improve visibility and aesthetics.",
        fogLightInstallationDesc: "Enhance visibility in foggy conditions with powerful fog lights.",
        mirrorReplacementDesc: "Replace broken or damaged mirrors with quality parts.",
        newArrivalsDesc: "Explore the latest and trendiest lighting collections.",
        usedPartsDesc: "Affordable, good quality used parts.",
        specialistBrandsDesc: "Expertise in Maruti, Honda, Tata, Hyundai, Toyota & more.",
        allOurServices: "All Our Services",
        learnMore: "Learn More",
        serviceDetail: "Service Details",
        benefits: "Benefits",
        estimatedTime: "Estimated Time:",
        productsTitle: "Our Products",
        productDetail: "Product Details",
        price: "Price:",
        specifications: "Specifications:",
        compatibility: "Compatibility:",
        generateNewImage: "Generate New Image",
        generatingImage: "Generating Image...",
        generatedImage: "Generated Image:",
        imageCouldNotBeGenerated: "Image could not be generated. Please try again.",
        failedToGenerateImage: "Failed to generate image:",
        aiProductInsights: "✨ AI Product Insights ✨",
        generatingInsights: "Generating insights...",
        productInsights: "Product Insights:",
        failedToGenerateInsights: "Failed to generate insights.",
        selectServiceType: "Select Service Type:",
        selectService: "Select Service",
        vehicleMake: "Vehicle Make (e.g. Maruti, Honda):",
        vehicleModel: "Vehicle Model (e.g. Swift, City):",
        appointmentDate: "Appointment Date:",
        appointmentTime: "Appointment Time:",
        yourName: "Your Name:",
        yourPhoneNumber: "Your Phone Number:",
        requiredFields: "Please fill in all required fields.",
        bookingSuccess: "Your appointment has been successfully booked. We will contact you soon.",
        bookingFailed: "Error booking appointment:",
        tryAgain: "Please try again.",
        bookingAppointment: "Booking Appointment...",
        confirmDeletion: "Confirm Deletion",
        areYouSureToDelete: "Are you sure you want to delete the appointment for",
        yesDelete: "Yes, Delete",
        noCancel: "No, Cancel",
        noAppointments: "You have no appointments.",
        bookOneNow: "Book one now!",
        vehicle: "Vehicle:",
        date: "Date:",
        time: "Time:",
        contactPerson: "Contact:",
        reschedule: "Reschedule",
        cancel: "Cancel",
        errorFetchingAppointments: "Error fetching appointments.",
        myAppointments: "My Appointments",
        aboutUs: "About Us",
        owner: "Owner:",
        aboutKohinoor: "About Kohinoor Lights",
        mission: "Our Mission",
        missionText: "To provide the best car lighting solutions and services, ensuring safety and style for our customers.",
        faqs: "Frequently Asked Questions",
        faq1Q: "What services do you offer?",
        faq1A: "We offer headlight restoration, replacement, fog light installation, mirror replacement, and custom lighting solutions.",
        faq2Q: "Which car brands do you specialize in?",
        faq2A: "We specialize in Maruti, Tata, Honda, Hyundai, Innova, Opel, Ford, Santro, Toyota, and more.",
        testimonials: "Customer Testimonials",
        testi1: "Excellent service! My car's headlights look brand new.",
        testi2: "Very professional and quick. Highly recommend Kohinoor Lights!",
        testi3: "Great selection of products and expert installation.",
        ourAddress: "Our Address",
        viewOnMap: "View on Map",
        phoneNumbers: "Phone Numbers",
        email: "Email",
        workingHours: "Working Hours",
        followUs: "Follow Us",
        mondayToSaturday: "Monday - Saturday: 9:00 AM - 7:00 PM",
        sunday: "Sunday: Closed",
        aiChat: "AI Chat",
        askAboutLights: "Ask anything about car lights or our services...",
        sendMessage: "Send Message",
        aiThinking: "AI is thinking...",
        aiChatIntro: "Hello! I am the AI Assistant for your Kohinoor Lights app. You can ask me anything about car lights or our services.",
        personalizedServiceSuggestion: "✨ Personalized Service Suggestion ✨",
        describeYourIssue: "Describe your car's issue or needs:",
        suggestServices: "Suggest Services",
        aiServiceSuggestion: "AI Service Suggestion:",
        noSuggestionFound: "No suggestion found. Please try again.",
        generatingSuggestion: "Generating suggestion...",
        appNotReady: "App is not ready. Please try again in a moment.",
        errorDeletingAppointment: "Error deleting appointment.",
        loadingAppointments: "Loading appointments..."
    },
    hi: {
        appName: "कोहिनूर लाइट्स",
        home: "होम",
        services: "सेवाएं",
        products: "उत्पाद",
        book: "बुक करें",
        myBookings: "मेरी बुकिंग्स",
        contactNav: "संपर्क करें",
        search: "खोजें...",
        userId: "यूज़र आईडी:",
        loadingApp: "एप्लिकेशन लोड हो रहा है...",
        welcomeTitle: "अपनी कार की रोशनी बढ़ाएं",
        welcomeSubtitle: "बेहतरीन हेडलाइट्स और सेवाओं के लिए वन-स्टॉप समाधान।",
        ourServices: "हमारी सेवाएं",
        featuredProducts: "खास प्रोडक्ट्स",
        view: "देखें",
        bookAppointment: "अपॉइंटमेंट बुक करें",
        contactUs: "हमसे संपर्क करें",
        headlightRestoration: "हेडलाइट रेस्टोरेशन",
        headlightReplacement: "हेडलाइट रिप्लेसमेंट",
        fogLightInstallation: "फॉग लाइट इंस्टॉलेशन",
        mirrorReplacement: "मिरर रिप्लेसमेंट",
        newArrivals: "नए आगमन",
        usedParts: "पुराने पार्ट्स",
        specialistBrands: "विशेषज्ञ ब्रांड्स",
        headlightRestorationDesc: "पुरानी हेडलाइट्स को उनकी मूल स्पष्टता और चमक में बहाल करें।",
        headlightReplacementDesc: "दृश्यता और सौंदर्यशास्त्र में सुधार के लिए नई हेडलाइट्स स्थापित करें।",
        fogLightInstallationDesc: "शक्तिशाली फॉग लाइट्स के साथ कोहरे की स्थिति में दृश्यता बढ़ाएं।",
        mirrorReplacementDesc: "टूटे या क्षतिग्रस्त मिरर्स को गुणवत्ता वाले पुर्जों से बदलें।",
        newArrivalsDesc: "नवीनतम और सबसे ट्रेंडिएस्ट लाइटिंग कलेक्शन का अन्वेषण करें।",
        usedPartsDesc: "किफायती, अच्छी गुणवत्ता वाले पुराने पुर्जे।",
        specialistBrandsDesc: "मारुति, होंडा, टाटा, हुंडई, टोयोटा और अन्य में विशेषज्ञता।",
        allOurServices: "हमारी सभी सेवाएं",
        learnMore: "और जानें",
        serviceDetail: "सेवा विवरण",
        benefits: "लाभ",
        estimatedTime: "अनुमानित समय:",
        productsTitle: "हमारे उत्पाद",
        productDetail: "उत्पाद विवरण",
        price: "मूल्य:",
        specifications: "विशेष विवरण:",
        compatibility: "संगतता:",
        generateNewImage: "नई इमेज जनरेट करें",
        generatingImage: "इमेज जनरेट हो रही है...",
        generatedImage: "जनरेटेड इमेज:",
        imageCouldNotBeGenerated: "इमेज जनरेट नहीं की जा सकी। कृपया पुनः प्रयास करें।",
        failedToGenerateImage: "इमेज जनरेट करने में विफल:",
        aiProductInsights: "✨ एआई उत्पाद अंतर्दृष्टि ✨",
        generatingInsights: "अंतर्दृष्टि जनरेट हो रही है...",
        productInsights: "उत्पाद अंतर्दृष्टि:",
        failedToGenerateInsights: "अंतर्दृष्टि जनरेट करने में विफल।",
        selectServiceType: "सेवा का प्रकार चुनें:",
        selectService: "सेवा चुनें",
        vehicleMake: "वाहन का ब्रांड (उदाहरण: Maruti, Honda):",
        vehicleModel: "वाहन का मॉडल (उदाहरण: Swift, City):",
        appointmentDate: "अपॉइंटमेंट की तारीख:",
        appointmentTime: "अपॉइंटमेंट का समय:",
        yourName: "आपका नाम:",
        yourPhoneNumber: "आपका फ़ोन नंबर:",
        requiredFields: "कृपया सभी आवश्यक फ़ील्ड भरें।",
        bookingSuccess: "आपकी अपॉइंटमेंट सफलतापूर्वक बुक हो गई है। हम जल्द ही आपसे संपर्क करेंगे।",
        bookingFailed: "अपॉइंटमेंट बुक करने में त्रुटि हुई:",
        tryAgain: "कृपया पुनः प्रयास करें।",
        bookingAppointment: "अपॉइंटमेंट बुक कर रहा है...",
        confirmDeletion: "डिलीशन की पुष्टि करें",
        areYouSureToDelete: "क्या आप वाकई के लिए अपॉइंटमेंट हटाना चाहते हैं?",
        yesDelete: "हां, हटा दें",
        noCancel: "नहीं, रद्द करें",
        noAppointments: "आपके पास कोई अपॉइंटमेंट नहीं है।",
        bookOneNow: "अभी एक बुक करें!",
        vehicle: "वाहन:",
        date: "तारीख:",
        time: "समय:",
        contactPerson: "संपर्क:",
        reschedule: "री-शेड्यूल करें",
        cancel: "कैंसिल करें",
        errorFetchingAppointments: "अपॉइंटमेंट लाने में त्रुटि हुई।",
        myAppointments: "मेरी अपॉइंटमेंट्स",
        aboutUs: "हमारे बारे में",
        owner: "मालिक:",
        aboutKohinoor: "कोहिनूर लाइट्स के बारे में",
        mission: "हमारा मिशन",
        missionText: "हमारे ग्राहकों के लिए सुरक्षा और स्टाइल सुनिश्चित करते हुए, सर्वोत्तम कार लाइटिंग समाधान और सेवाएं प्रदान करना।",
        faqs: "अक्सर पूछे जाने वाले प्रश्न",
        faq1Q: "आप कौन सी सेवाएं प्रदान करते हैं?",
        faq1A: "हम हेडलाइट रेस्टोरेशन, रिप्लेसमेंट, फॉग लाइट इंस्टॉलेशन, मिरर रिप्लेसमेंट और कस्टम लाइटिंग समाधान प्रदान करते हैं।",
        faq2Q: "आप किन कार ब्रांडों में विशेषज्ञ हैं?",
        faq2A: "हम मारुति, टाटा, होंडा, हुंडई, इनोवा, ओपल, फोर्ड, सैंट्रो, टोयोटा और अन्य में विशेषज्ञ हैं।",
        testimonials: "ग्राहक प्रशंसापत्र",
        testi1: "उत्कृष्ट सेवा! मेरी कार की हेडलाइट्स बिल्कुल नई जैसी दिखती हैं।",
        testi2: "बहुत पेशेवर और तेज़। कोहिनूर लाइट्स की अत्यधिक अनुशंसा करता हूँ!",
        testi3: "उत्पादों का शानदार चयन और विशेषज्ञ स्थापना।",
        ourAddress: "हमारा पता",
        viewOnMap: "मैप पर देखें",
        phoneNumbers: "फोन नंबर",
        email: "ईमेल",
        workingHours: "कार्य समय",
        followUs: "हमें फॉलो करें",
        mondayToSaturday: "सोमवार - शनिवार: सुबह 9:00 बजे - शाम 7:00 बजे",
        sunday: "रविवार: बंद",
        aiChat: "एआई चैट",
        askAboutLights: "कार की लाइटों या हमारी सेवाओं के बारे में कुछ भी पूछें...",
        sendMessage: "संदेश भेजें",
        aiThinking: "एआई सोच रहा है...",
        aiChatIntro: "नमस्ते! मैं आपके Kohinoor Lights ऐप का AI असिस्टेंट हूँ। आप मुझसे कार लाइट्स या हमारी सेवाओं के बारे में कुछ भी पूछ सकते हैं।",
        personalizedServiceSuggestion: "✨ व्यक्तिगत सेवा सुझाव ✨",
        describeYourIssue: "अपनी कार की समस्या या ज़रूरतें बताएं:",
        suggestServices: "सेवाएं सुझाएं",
        aiServiceSuggestion: "एआई सेवा सुझाव:",
        noSuggestionFound: "कोई सुझाव नहीं मिला। कृपया पुनः प्रयास करें।",
        generatingSuggestion: "सुझाव जनरेट हो रहा है...",
        appNotReady: "ऐप तैयार नहीं है। कृपया थोड़ी देर में पुनः प्रयास करें।",
        errorDeletingAppointment: "अपॉइंटमेंट हटाने में त्रुटि हुई।",
        loadingAppointments: "अपॉइंटमेंट लोड हो रहे हैं..."
    },
    mr: {
        appName: "कोहिनूर लाइट्स",
        home: "मुख्यपृष्ठ",
        services: "सेवा",
        products: "उत्पाद",
        book: "बुकिंग करा",
        myBookings: "माझे बुकिंग",
        contactNav: "संपर्क साधा",
        search: "शोधा...",
        userId: "वापरकर्ता आयडी:",
        loadingApp: "ॲप्लिकेशन लोड होत आहे...",
        welcomeTitle: "तुमच्या कारची दृष्टी सुधारा",
        welcomeSubtitle: "उत्कृष्ट हेडलाइट्स आणि सेवांसाठी एकच ठिकाण.",
        ourServices: "आमच्या सेवा",
        featuredProducts: "वैशिष्ट्यीकृत उत्पादने",
        view: "पहा",
        bookAppointment: "अपॉइंटमेंट बुक करा",
        contactUs: "आमच्याशी संपर्क साधा",
        headlightRestoration: "हेडलाइट पुनर्संचयन",
        headlightReplacement: "हेडलाइट बदलणे",
        fogLightInstallation: "फॉग लाइट इन्स्टॉलेशन",
        mirrorReplacement: "आरसा बदलणे",
        newArrivals: "नवीन आगमन",
        usedParts: "वापरलेले भाग",
        specialistBrands: "विशेषज्ञ ब्रँड्स",
        headlightRestorationDesc: "मंद झालेल्या हेडलाइट्सला त्यांची मूळ स्पष्टता आणि चमक परत आणा.",
        headlightReplacementDesc: "दृश्यमानता आणि सौंदर्य सुधारण्यासाठी नवीन हेडलाइट्स स्थापित करा.",
        fogLightInstallationDesc: "शक्तिशाली फॉग लाइट्समुळे धुक्याच्या स्थितीत दृश्यमानता वाढवा.",
        mirrorReplacementDesc: "तुटलेले किंवा खराब झालेले आरसे दर्जेदार भागांनी बदला.",
        newArrivalsDesc: "नवीनतम आणि ट्रेंडिएस्ट लाइटिंग कलेक्शन एक्सप्लोर करा.",
        usedPartsDesc: "परवडणारे, चांगल्या दर्जाचे वापरलेले भाग.",
        specialistBrandsDesc: "मारुती, होंडा, हुंडई, टोयोटा आणि इतरांमध्ये तज्ञ.",
        allOurServices: "आमच्या सर्व सेवा",
        learnMore: "अधिक जाणून घ्या",
        serviceDetail: "सेवा तपशील",
        benefits: "फायदे",
        estimatedTime: "अंदाजित वेळ:",
        productsTitle: "आमची उत्पादने",
        productDetail: "उत्पादनाचे तपशील",
        price: "किंमत:",
        specifications: "तपशील:",
        compatibility: "सुसंगतता:",
        generateNewImage: "नवीन प्रतिमा तयार करा",
        generatingImage: "प्रतिमा तयार होत आहे...",
        generatedImage: "तयार केलेली प्रतिमा:",
        imageCouldNotBeGenerated: "प्रतिमा तयार केली जाऊ शकली नाही. कृपया पुन्हा प्रयत्न करा.",
        failedToGenerateImage: "प्रतिमा तयार करण्यात अयशस्वी:",
        aiProductInsights: "✨ एआय उत्पादनाची माहिती ✨",
        generatingInsights: "माहिती तयार होत आहे...",
        productInsights: "उत्पादनाची माहिती:",
        failedToGenerateInsights: "माहिती तयार करण्यात अयशस्वी.",
        selectServiceType: "सेवेचा प्रकार निवडा:",
        selectService: "सेवा निवडा",
        vehicleMake: "वाहनाचा ब्रँड (उदा. मारुती, होंडा):",
        vehicleModel: "वाहनाचा मॉडेल (उदा. स्विफ्ट, सिटी):",
        appointmentDate: "अपॉइंटमेंटची तारीख:",
        appointmentTime: "अपॉइंटमेंटची वेळ:",
        yourName: "तुमचे नाव:",
        yourPhoneNumber: "तुमचा फोन नंबर:",
        requiredFields: "कृपया सर्व आवश्यक फील्ड भरा.",
        bookingSuccess: "तुमची अपॉइंटमेंट यशस्वीरित्या बुक झाली आहे. आम्ही लवकरच तुमच्याशी संपर्क साधू.",
        bookingFailed: "अपॉइंटमेंट बुक करताना त्रुटी आली:",
        tryAgain: "कृपया पुन्हा प्रयत्न करा.",
        bookingAppointment: "अपॉइंटमेंट बुक करत आहे...",
        confirmDeletion: "हटविण्याची पुष्टी करा",
        areYouSureToDelete: "तुम्ही अपॉइंटमेंट हटवू इच्छिता याची खात्री आहे का?",
        yesDelete: "होय, हटवा",
        noCancel: "नाही, रद्द करा",
        noAppointments: "तुमच्याकडे कोणतीही अपॉइंटमेंट नाही.",
        bookOneNow: "आता एक बुक करा!",
        vehicle: "वाहन:",
        date: "तारीख:",
        time: "वेळ:",
        contactPerson: "संपर्क:",
        reschedule: "पुनर्नियोजित करा",
        cancel: "रद्द करा",
        errorFetchingAppointments: "अपॉइंटमेंट मिळवताना त्रुटी आली.",
        myAppointments: "माझे बुकिंग",
        aboutUs: "आमच्याबद्दल",
        owner: "मालिक:",
        aboutKohinoor: "कोहिनूर लाइट्स बद्दल",
        mission: "आमचे ध्येय",
        missionText: "आमच्या ग्राहकांना सुरक्षितता आणि शैली सुनिश्चित करून, सर्वोत्तम कार लाइटिंग सोल्यूशन्स आणि सेवा प्रदान करणे.",
        faqs: "वारंवार विचारले जाणारे प्रश्न",
        faq1Q: "तुम्ही कोणत्या सेवा प्रदान करता?",
        faq1A: "आम्ही हेडलाइट पुनर्संचयन, बदलणे, फॉग लाइट इन्स्टॉलेशन, आरसा बदलणे आणि कस्टम लाइटिंग सोल्यूशन्स प्रदान करतो.",
        faq2Q: "तुम्ही कोणत्या कार ब्रँडमध्ये तज्ञ आहात?",
        faq2A: "आम्ही मारुती, टाटा, होंडा, हुंडई, इनोवा, ओपल, फॉर्ड, सँट्रो, टोयोटा आणि इतरांमध्ये तज्ञ आहोत.",
        testimonials: "ग्राहक प्रशंसापत्रे",
        testi1: "उत्कृष्ट सेवा! माझ्या कारच्या हेडलाइट्स अगदी नवीन दिसतात.",
        testi2: "खूप व्यावसायिक आणि जलद. कोहिनूर लाइट्सची शिफारस करतो!",
        testi3: "उत्पादनांची उत्तम निवड आणि तज्ञ स्थापना.",
        ourAddress: "आमचा पत्ता",
        viewOnMap: "नकाशावर पहा",
        phoneNumbers: "फोन नंबर",
        email: "ईमेल",
        workingHours: "कामाचे तास",
        followUs: "आमचे अनुसरण करा",
        mondayToSaturday: "सोमवार - शनिवार: सकाळी 9:00 - संध्याकाळी 7:00",
        sunday: "रविवार: बंद",
        aiChat: "एआय चॅट",
        askAboutLights: "कार लाइट्स किंवा आमच्या सेवांबद्दल काहीही विचारा...",
        sendMessage: "संदेश पाठवा",
        aiThinking: "एआय विचार करत आहे...",
        aiChatIntro: "नमस्कार! मी तुमच्या Kohinoor Lights ॲपचा AI असिस्टंट आहे। तुम्ही मला कार लाइट्स किंवा आमच्या सेवांबद्दल काहीही विचारू शकता।",
        personalizedServiceSuggestion: "✨ वैयक्तिक सेवा सूचना ✨",
        describeYourIssue: "तुमच्या कारची समस्या किंवा गरजा वर्णन करा:",
        suggestServices: "सेवा सुचवा",
        aiServiceSuggestion: "एआय सेवा सूचना:",
        noSuggestionFound: "कोणतीही सूचना सापडली नाही। कृपया पुन्हा प्रयत्न करा।",
        generatingSuggestion: "सूचना तयार होत आहे...",
        appNotReady: "ॲप तयार नाही। कृपया थोड्या वेळात पुन्हा प्रयत्न करा।",
        errorDeletingAppointment: "अपॉइंटमेंट हटवताना त्रुटी आली।",
        loadingAppointments: "अपॉइंटमेंट लोड होत आहेत..."
    }
};

// --- Context for Firebase, User Data, and Language ---
const AppContext = createContext();

const AppProvider = ({ children }) => {
    const [db, setDb] = useState(null);
    const [auth, setAuth] = useState(null);
    const [userId, setUserId] = useState(null);
    const [isAuthReady, setIsAuthReady] = useState(false);
    const [language, setLanguage] = useState('hi'); // Default language is Hindi

    const t = (key) => translations[language][key] || key; // Translation function

    useEffect(() => {
        const initializeFirebase = async () => {
            try {
                // Access __app_id and __firebase_config directly from the global scope (Canvas environment)
                const appId = typeof __app_id !== 'undefined' ? __app_id : 'default-app-id';
                const firebaseConfig = JSON.parse(typeof __firebase_config !== 'undefined' ? __firebase_config : '{}');

                if (Object.keys(firebaseConfig).length === 0 || !firebaseConfig.projectId) {
                    console.error("Firebase config is empty or invalid. Please ensure __firebase_config is correctly set.");
                    const dummyConfig = {
                        apiKey: "dummy-key",
                        authDomain: "dummy-domain.firebaseapp.com",
                        projectId: "dummy-project",
                        storageBucket: "dummy-bucket.appspot.com",
                        messagingSenderId: "1234567890",
                        appId: "1:1234567890:web:abcdef1234567890"
                    };
                    const app = initializeApp(dummyConfig);
                    const authInstance = getAuth(app);
                    const dbInstance = getFirestore(app);
                    setAuth(authInstance);
                    setDb(dbInstance);
                } else {
                    const app = initia